# redis/master.conf
port 6379
bind 0.0.0.0
protected-mode no

# Perzistentnost
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfsync everysec

# Replikacija
min-replicas-to-write 0
min-replicas-max-lag 10

# Replication backlog (1MB default)
repl-backlog-size 1mb
repl-backlog-ttl 3600

# Performanse
maxmemory 256mb
maxmemory-policy allkeys-lru
activerehashing yes
lazyfree-lazy-eviction yes

# Logging
loglevel notice
