# redis/replica.conf
bind 0.0.0.0
protected-mode no

# Replikacija
replica-read-only yes
replica-lazy-flush yes
repl-diskless-sync no
repl-diskless-sync-delay 5

# Perzistentnost (opciono na replici)
appendonly yes
appendfsync everysec

# Performanse
maxmemory 256mb
maxmemory-policy allkeys-lru
lazyfree-lazy-eviction yes

# Logging
loglevel notice
