# redis/sentinel.conf
bind 0.0.0.0
protected-mode no

# Praćenje mastera
# quorum = 2 (od 3 sentinel-a moraju se složiti da je master dole)
sentinel monitor mymaster redis-master 6379 2

# Vreme čekanja pre proglašenja SDOWN (5 sekundi)
sentinel down-after-milliseconds mymaster 5000

# Maksimalno vreme za failover
sentinel failover-timeout mymaster 30000

# Koliko replika može istovremeno sinhronizovati novog mastera
sentinel parallel-syncs mymaster 1

# Notifikacije
# sentinel notification-script mymaster /path/to/script.sh

loglevel notice
